"""Stable identifiers shared by capability classification and surface adapters."""

CAP_FILES = "files"
CAP_FILE_ORGANIZATION = "file_organization"
CAP_TRANSFER = "transfer"
CAP_SCREEN_OBSERVATION = "screen_observation"
CAP_CURRENT_FACTS = "current_facts"
CAP_SCHEDULING = "scheduling"
CAP_MCP = "mcp"
CAP_CODE_GRAPH = "code_graph"
CAP_PERCEPTION = "perception"
CAP_DESIGN = "design"
CAP_COMPUTER_CONTROL = "computer_control"
CAP_PHONE = "phone"
CAP_SYSTEMCARE = "systemcare"
CAP_WEB = "web"
CAP_GITHUB_REPO = "github_repo"
CAP_PROFILE = "profile"
CAP_LIFE = "life"
CAP_MIGRATION = "migration"
CAP_VISUALIZATION = "visualization"
