(function(){
'use strict';
const $=s=>document.querySelector(s), initial=window.MO_CARE_INITIAL;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=n=>initial.icons[n]||initial.icons.details;
const mark=initial.mark;
const state={context:'machine',target:'',view:'overview',section:'health',manage:'services',clean:'caches',data:null,selected:new Set(),registrySelected:new Set(),plan:null,busy:false,signature:'',registryDeep:false,serverTargets:[],quickActive:'',quickDone:'',quickReceipt:'',pendingRepair:'',targetInspection:'',pageKey:'',scanMode:null,scanRequest:null,inspectRequest:'',scanPanelHTML:''};
const sectionLabels={health:'Health',indexes:'Indexes',coverage:'Coverage',caches:'Caches',service:'Service & startup',logs:'Logs',repair:'Maintenance review',dependencies:'Manifests & dependencies',storage:'Storage'};
const names={machine:'This machine',mo:'MO runtime',server:'MO servers',projects:'Projects'};
const scanDomains={storage:['Storage & apps','folder'],health:['Windows health','details'],startup:['Services & startup','tools'],performance:['Performance','refresh'],registry:['Registry','search']};
const checkLabels={complete:'Checked',limited:'Limited',unavailable:'Unavailable',failed:'Failed',cancelled:'Stopped',active:'Checking',pending:'Queued',unchecked:'Not checked',not_run:'Not run',stale:'Older result'};
const fmt=n=>{if(n==null)return '—';let i=0;while(n>=1024&&i<4){n/=1024;i++}return `${n.toFixed(i&&n<10?1:0)} ${['B','KB','MB','GB','TB'][i]}`};
const time=n=>n?new Date(n*1000).toLocaleString():'Not checked';
const api=()=>window.pywebview.api;
let toastTimer,pollTimer,refreshTimer,drawerOrigin,hostVisible=true,iconObserver,iconQueue=Promise.resolve();
const canRefresh=()=>hostVisible&&!document.hidden;
function notify(text){const e=$('#toast');e.textContent=String(text);e.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.hidden=true,3500)}
async function call(method,...args){try{return await api()[method](...args)}catch(e){notify(e.message||String(e));throw e}}
function button(label,action,primary=false,attrs=''){return `<button class="button${primary?' primary':''}" data-do="${action}" ${attrs}>${label}</button>`}
function askMO(section,selection=null){if(['server','projects'].includes(state.context)&&!state.target)return '';return button('Ask MO','maintenance-review',false,`data-context-review="${esc(state.context)}" data-section="${esc(section)}" data-target="${esc(state.target)}" data-selection="${esc(JSON.stringify(selection))}"`)}
function itemSymbol(section,index,o){return `<span class="row-symbol" ${['apps','startup'].includes(section)?`data-item-icon="${index}" data-section="${esc(section)}" data-observed="${o.observed_at}"`:''}>${icon(section==='startup'?'refresh':'tools')}</span>`}
function loadItemIcons(){if(typeof IntersectionObserver==='undefined')return;iconObserver?.disconnect();iconObserver=new IntersectionObserver(entries=>{for(const entry of entries){if(!entry.isIntersecting)continue;const e=entry.target;iconObserver.unobserve(e);iconQueue=iconQueue.then(async()=>{if(!e.isConnected||!canRefresh())return;const src=await call('item_icon',e.dataset.section,Number(e.dataset.itemIcon),Number(e.dataset.observed));if(src&&e.isConnected)e.innerHTML=`<img src="${esc(src)}" width="24" height="24" alt="">`;}).catch(()=>{});}});document.querySelectorAll('[data-item-icon]').forEach(e=>iconObserver.observe(e));}
function badge(label){const tone=['good','ok','Keep','completed','measured'].includes(label)?'ok':['Review','attention','warn','partial','stale'].includes(label)?'warn':'';return `<span class="tag ${tone}">${esc(label)}</span>`}
function checkedState(o){return o.state==='measured'?'complete':o.state==='partial'?'limited':o.state==='failed'?'failed':'unavailable'}
function scanEvidence(){
 const data=state.data||{},active=data.status?.active_operation||{},p=data.progress||{},busy=Boolean(state.busy||data.status?.active);
 const running=busy&&state.context==='machine'&&(active.kind?active.kind==='scanning':Boolean(state.scanRequest||p.phase==='scan'||p.phase==='calibrate'));
 const last=state.context==='machine'?data.status?.last_scan:null;
 let checks=running?(p.checks?.length?p.checks:(state.scanRequest?(data.scan_scopes?.[state.scanRequest.mode]||[]).filter(c=>state.scanRequest.allChecks||!c.section):[]).map(c=>({...c,state:'pending'}))):(last?.checks||[]).map(c=>({...c}));
 if(!running&&!checks.length&&last)checks=(last.findings||[]).map(f=>({rule_id:f.rule_id,title:f.title,domain:f.domain,section:f.evidence?.section||'',state:f.evidence?.available===false?'unavailable':f.evidence?.coverage_state==='partial'?'limited':'complete',at:last.completed_at,detail:f.summary}));
 if(!running)for(const [section,o] of Object.entries(data.observations||{})){
  if(section==='resources')continue;
  const existing=checks.find(c=>c.section===section),rule=(data.scan_scopes?.advanced||[]).find(c=>c.section===section);
  if(existing&&existing.at>=o.observed_at)continue;
  const row={rule_id:'inspect.'+section,title:rule?.title||section.replaceAll('_',' '),domain:rule?.domain||'health',section,state:checkedState(o),at:o.observed_at,detail:o.detail,stale:o.stale};
  if(existing)Object.assign(existing,row);else checks.push(row);
 }
 const request=state.inspectRequest,section=active.kind?(active.kind==='inspecting'&&active.context===state.context?active.section:''):request?.context===state.context&&request.target===state.target?request.section:p.phase==='inspection'&&p.context===state.context?p.section:'';
 if(busy&&!running&&section){const row=checks.find(c=>c.section===section);if(row){row.state='active';row.stale=false;}else checks.push({rule_id:'inspect.'+section,title:section.replaceAll('_',' '),domain:'health',section,state:'active'});}
 if(!checks.length&&state.context==='machine')checks=(data.scan_scopes?.[state.scanMode]||[]).map(c=>({...c,state:'unchecked'}));
 const now=Date.now()/1000;
 checks=checks.map(c=>({...c,state:c.state==='pending'&&!running?'not_run':c.state,stale:c.stale||Boolean(!running&&c.at&&Number.isFinite(data.evidence_freshness_seconds)&&now-c.at>data.evidence_freshness_seconds&&['complete','limited'].includes(c.state))}));
 return {checks,running,busy,last,label:running?(p.label||'Preparing machine checks…'):section&&busy?'Checking '+section.replaceAll('_',' '):'',fraction:running&&p.phase==='scan'?p.fraction||0:0};
}
function checkSymbol(status){return `<span class="check-symbol ${esc(status)}" aria-hidden="true"></span>`}
function sectionEvidence(section){const c=scanEvidence().checks.find(c=>c.section===section);const status=c?(c.stale?'stale':c.state):'unchecked';return `<span class="section-evidence" data-scan-section="${esc(section)}" title="${esc(checkLabels[status])}">${checkSymbol(status)}<span>${esc(checkLabels[status])}</span></span>`}
function repairEligibility(){
 const last=state.data?.status?.last_scan,receipt=state.data?.status?.last_receipt;
 if(!last||!['ready','completed'].includes(last.state))return {count:0,registryAt:null,changed:false};
 const changed=receipt?.created_at>=last?.completed_at&&(receipt.checks||[]).some(c=>c.state==='complete'&&(c.finding_id||c.rule_id==='action.registry_remove'));
 const registry=observation('registry');
 return {count:changed?0:findings().filter(f=>f.selectable&&f.action!=='review'&&f.candidate_count>0).length+(actionableObservation(registry)?(registry.rows||[]).filter(r=>r.eligible).length:0),registryAt:actionableObservation(registry)?registry.observed_at:null,changed};
}
function operationEvidence(){
 const scan=scanEvidence(),p=state.data?.progress||{},active=state.data?.status?.active_operation||{},receipt=state.data?.status?.last_receipt;
 const repairing=scan.busy&&(active.kind==='applying'||['apply','verify'].includes(p.phase));
 const repairResult=state.context==='machine'&&!scan.busy&&receipt?.checks?.length&&receipt.completed_at>=(scan.last?.completed_at||0);
 const checks=repairing?(p.checks||[]):repairResult?receipt.checks.map(c=>({...c,state:c.state==='pending'?'not_run':c.state})):scan.checks;
 return {...scan,checks,repairing,repairResult,receipt,working:scan.running||repairing,
  fraction:repairing?p.fraction||0:scan.fraction,
  label:repairing?p.label||'Preparing reviewed repairs…':scan.label,
  startedAt:active.started_at||(repairing?checks.find(c=>c.started_at)?.started_at:scan.running?scan.last?.started_at:0)||0};
}
function scanPanel(){
 const evidence=operationEvidence(),{checks,running,busy,last,repairing,repairResult,receipt,working}=evidence;
 const finished=checks.filter(c=>['complete','limited','unavailable','failed'].includes(c.state)),limits=finished.filter(c=>c.state!=='complete'),older=checks.filter(c=>c.stale);
 const scope=state.data?.scan_scopes?.[state.scanMode]||[],groups=[...new Set(checks.map(c=>c.domain))],eligible=repairEligibility();
 const stopped=!working&&(repairResult?['cancelled','failed'].includes(receipt.state):last&&['cancelled','failed'].includes(last.state));
 const title=repairing?'Repairing reviewed findings':running?'Scanning your machine':repairResult?receipt.state==='cancelled'?'Repairs stopped':receipt.verified?'Repairs complete':'Repairs need review':busy&&evidence.label?evidence.label:stopped?'Scan '+(last.state==='cancelled'?'stopped':'failed'):finished.length?'Saved check results':'Ready to check';
 const subtitle=working?evidence.label:repairResult?`${receipt.applied_steps.length} applied · ${receipt.skipped_steps.length} unchanged · ${receipt.failed_steps.length} failed`:finished.length?`${finished.length} ${finished.length===1?'check':'checks'} recorded${limits.length?' · '+limits.length+' with limits or errors':''}${older.length?' · '+older.length+' older':''}`:'Choose your scope. Results will stay here after each check.';
 const count=checks.length&&(working||repairResult)?`${finished.length} / ${checks.length}`:finished.length?String(finished.length):'—';
 const percent=working?Math.round(evidence.fraction*100):checks.length?Math.round(finished.length/checks.length*100):0;
 const resultState=working?'active':stopped?'cancelled':limits.length?'limited':finished.length?'complete':'unchecked';
 return `<div class="scan-heading"><div class="scan-summary">${checkSymbol(resultState)}<div><h2>${esc(title)}</h2><p role="status">${esc(subtitle)}</p></div><strong class="scan-count">${count}<small>${repairing||repairResult?'steps':running?'checks':'recorded'}</small></strong></div><div class="scan-controls">${state.context==='machine'?`<label class="scan-advanced"><input id="scan-advanced" type="checkbox" ${state.scanMode==='advanced'?'checked':''} ${busy?'disabled':''}>Advanced</label>${button(busy?'Cancel':eligible.count?'Repair all · '+eligible.count+' findings':last?'Scan again':'Scan all',!busy&&eligible.count?'repair-all':'scan-all',!busy)}<button class="quiet" data-do="scan-scope">Scope ${icon('chevron_right')}</button>`:button(busy?'Cancel':'Inspect current','scan',!busy)}</div></div>
 <div class="operation-meta"><span>${working?`${percent}% complete · ${checks.filter(c=>c.state==='pending').length} queued`:repairResult?esc(receipt.detail):eligible.count?`${eligible.count} actionable findings · Repair all opens one review`:eligible.changed?'Repair results saved · refresh the scan before another repair':''}</span><span id="scan-elapsed" data-started="${working?evidence.startedAt:0}">${working?'Elapsed 0s':repairResult?time(receipt.completed_at):''}</span></div>
 <div class="scan-track ${working&&!evidence.fraction?'is-waiting':''}" ${working?'role="progressbar" aria-label="'+(repairing?'Reviewed repairs':'Machine scan')+'" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+percent+'"':''}><i style="width:${percent}%"></i></div>
 ${working&&checks.length?`<div class="operation-steps" aria-label="${repairing?'Repair':'Scan'} steps">${checks.map(c=>`<span class="operation-step ${esc(c.state)}" title="${esc(c.title+' · '+checkLabels[c.state])}"><span class="sr-only">${esc(c.title+' · '+checkLabels[c.state])}</span></span>`).join('')}</div>`:''}
 ${groups.length?`<div class="scan-groups">${groups.map(domain=>{const rows=checks.filter(c=>c.domain===domain),done=rows.filter(c=>['complete','limited','unavailable','failed'].includes(c.state)),active=rows.some(c=>c.state==='active'),issues=done.filter(c=>c.state!=='complete'),stale=rows.some(c=>c.stale),status=active?'active':issues.some(c=>c.state==='failed')?'failed':issues.length?'limited':stale?'stale':done.length===rows.length?'complete':'unchecked',info=scanDomains[domain]||[domain,'details'];return `<button class="scan-group ${status}" data-scan-domain="${esc(domain)}"><span class="scan-group-icon">${icon(info[1])}</span><span><strong>${esc(repairing||repairResult||state.context==='machine'?info[0]:'Inspected sections')}</strong><small>${active?(repairing?'Repairing…':'Checking…'):done.length?`${done.length} / ${rows.length} finished${issues.length?' · '+issues.length+' limits':''}${stale?' · older':''}`:'Not checked'}</small></span>${checkSymbol(status)}</button>`}).join('')}</div>`:''}
 <div class="scan-scope-note"><span>${repairing||repairResult?'Exact reviewed plan · verified outcomes retained':state.context==='machine'?`${scope.length} enabled ${state.scanMode==='advanced'?'Advanced':'Safe'} checks · read-only`:esc(names[state.context])+' · selected target only'}${last&&!working&&!repairResult?' · Last scan '+time(last.completed_at):''}</span><small>${repairing||repairResult?'Before / after and recovery are in Activity.':'Checked means inspected; review findings before changes.'}</small></div>`;
}
function renderScanPanel(){
 const panel=$('#scan-monitor');if(!panel||!state.data)return;const html=scanPanel();
 if(html!==state.scanPanelHTML){const focused=document.activeElement?.id;panel.innerHTML=html;state.scanPanelHTML=html;if(focused==='scan-advanced')$('#scan-advanced')?.focus();}
 const elapsed=$('#scan-elapsed'),started=Number(elapsed?.dataset?.started);if(started)elapsed.textContent='Elapsed '+sessionDuration(Date.now()/1000-started);
 document.querySelectorAll('[data-scan-section]').forEach(e=>{const c=scanEvidence().checks.find(c=>c.section===e.dataset.scanSection),s=c?(c.stale?'stale':c.state):'unchecked';e.innerHTML=checkSymbol(s)+`<span>${esc(checkLabels[s])}</span>`;e.title=checkLabels[s]});
}
async function repairAll(){if(state.busy)return;const eligible=repairEligibility();if(!eligible.count)return notify('No current actionable repairs.');showPlan(await call('repair_plan',state.data.status.last_scan.scan_id,eligible.registryAt));}
function scanDetails(domain){const rows=operationEvidence().checks.filter(c=>c.domain===domain);openDrawer(scanDomains[domain]?.[0]||'Inspection results',`<p>Recorded checks and their actual coverage. Nothing is applied by scanning.</p><div class="panel">${rows.map(c=>`<button class="scan-check-row" data-scan-check="${esc(c.step_id||c.rule_id)}">${checkSymbol(c.state)}<span><strong>${esc(c.title)}</strong><small>${esc(c.detail||'No result recorded yet.')}</small><small>${c.at?time(c.at)+' · ':''}${esc(checkLabels[c.state])}${c.stale?' · older result':''}${c.elapsed_ms!=null?' · '+(c.elapsed_ms/1000).toFixed(1)+'s':''}</small></span>${icon('chevron_right')}</button>`).join('')}</div>`)}
function scanScope(){const scope=state.data?.scan_scopes?.[state.scanMode]||[];openDrawer(`${state.scanMode==='advanced'?'Advanced':'Safe'} scan scope`,`<p>${scope.length} enabled checks. Advanced options and category exclusions follow Settings. Administrator-only checks report unavailable without automatically requesting elevation. Root and volume-specific checks remain in Storage and Repair.</p><div class="panel">${scope.map(c=>`<div class="list-row"><span class="row-copy">${esc(c.title)}</span>${badge('read-only')}</div>`).join('')}</div>${button(state.busy?'Cancel current operation':'Scan this scope','scan-all',!state.busy)}${button('Configure scope','settings')}`)}
async function scanAll(){if(state.busy||state.data?.status?.active)return scan();if(state.context!=='machine')return scan();const r=await call('scan',state.scanMode,true);if(r.started){state.scanRequest={mode:state.scanMode,allChecks:true};state.inspectRequest='';state.data.progress={};state.busy=true;closeDrawer();renderStatus();schedulePoll()}else notify('Another SystemCare operation is active')}
function heading(title,sub,action=''){return `<div class="page-heading"><div><p class="eyebrow">${names[state.context]}</p><h1>${title}</h1><p class="subtitle">${sub}</p></div><div class="heading-action">${action}</div></div>`}
function observation(section){return state.data?.observations?.[section]||null}
function actionableObservation(o){return Boolean(o&&!o.stale&&['measured','partial'].includes(o.state))}
function findings(){return state.context==='machine'?(state.data?.status?.last_scan?.findings||[]):[]}
function openDrawer(title,body){$('#drawer').classList.remove('settings-drawer');if($('#drawer').hidden)drawerOrigin=document.activeElement;$('#drawer').innerHTML=`<div class="drawer-header"><h2>${esc(title)}</h2><button class="icon-button" data-do="close" aria-label="Close details">${icon('close')}</button></div>${body}`;$('#scrim').hidden=false;$('#drawer').hidden=false;$('#drawer').scrollTop=0;$('#drawer').querySelector('button')?.focus();loadItemIcons()}
function closeDrawer(){state.targetInspection='';$('#drawer').hidden=true;$('#scrim').hidden=true;if(drawerOrigin?.isConnected)drawerOrigin.focus()}
async function requestClose(){const r=await call('window_control','close');if(r?.busy)openDrawer('Close SystemCare?',`<p>An operation is running. Choose how to close.</p><p class="evidence-note">Stopping waits for the current safe boundary. Background work uses MO’s existing tray, reports its saved result, then exits. Reopening keeps the window available.</p>${state.data?.preferences.notifications===false?'<p class="evidence-note">Notifications are off in Settings; results will be saved for your next visit.</p>':''}${button(state.data?.preferences.notifications===false?'Finish in background':'Finish in background and notify','background-close',true)}${button('Stop scan and close','stop-close')}${button('Keep open','close')}`)}
window.moCareRequestClose=requestClose;
function noEvidence(section){const o=observation(section);return `<div class="panel"><div class="empty">${o?.detail?esc(o.detail):'No current result for this target.'}<br><small>${o?`Observed ${time(o.observed_at)} · ${esc(o.state)}`:'Inspection starts when you request it.'}</small></div></div>`}
function resource(label,value,unit){return `<div class="resource"><label>${label}</label><strong>${esc(value)}</strong><small>${esc(unit)}</small></div>`}
function sessionDuration(seconds){const value=Math.max(0,Number(seconds)||0),hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60);return hours?`${hours}h ${minutes}m`:minutes?`${minutes}m`:`${Math.floor(value)}s`}
function metricPercent(value){return Number.isFinite(value)?`${Math.round(value)}%`:'—'}
function gameSessionPanel(){
 const session=state.data?.game_session;if(!session||session.state==='inactive')return '';
 const active=session.state==='active',recovery=session.state==='recovery_required',restored=session.state==='restored';
 const metrics=session.metrics||{},baseline=metrics.baseline||{},current=metrics.current||{};
 const stateLabel=active?'Active':recovery?'Recovery required':'Restored';
 const itemRows=(session.items||[]).map(item=>`<div class="game-session-item"><span class="session-state-dot ${esc(item.state)}"></span><span><strong>${esc(item.label)}</strong><small>${esc(item.detail)}</small></span></div>`).join('');
 return `<section class="game-session-card ${esc(session.state)}" aria-label="Game Session"><div class="game-session-head"><div><p class="eyebrow">Game Session</p><h2>${active?'Focused session running':recovery?'Restore the captured originals':'Last session restored'}</h2><p>${active?'Windows state is protected by the recovery journal.':recovery?'A previous session did not finish restoring cleanly.':'The recorded Windows state passed its restoration checks.'}</p></div><span class="session-state-tag ${recovery?'attention':restored?'restored':'active'}"><i></i>${stateLabel}</span></div><div class="game-session-metrics"><div><label>SESSION</label><strong>${sessionDuration(session.duration_seconds)}</strong><small>${active?'elapsed':'recorded duration'}</small></div><div><label>CPU NOW</label><strong>${metricPercent(current.cpu_percent)}</strong><small>start ${metricPercent(baseline.cpu_percent)}</small></div><div><label>MEMORY NOW</label><strong>${metricPercent(current.memory_percent)}</strong><small>start ${metricPercent(baseline.memory_percent)}</small></div><div><label>RESOURCE STATE</label><strong>${esc(session.resource_state||'unknown')}</strong><small>${metrics.stale?'older reading':'existing refresh'}</small></div></div><div class="game-session-items">${itemRows}</div><div class="game-session-foot"><p>Readings reuse SystemCare’s visible refresh and do not establish FPS gains.</p>${button(active||recovery?'Stop & restore':'Review new session','game-session-review',active||recovery)}</div></section>`;
}
const quicks={machine:[['refresh','Desktop refresh','Refresh shell visuals','No apps closed','refresh'],['icons','Thumbnail caches','Review rebuildable files','Review exact changes','convert'],['integrity','System check','Inspect Windows integrity','Checks and repairs separated','details'],['game','Game Mode','One global on/off control','Original state retained','tools']],mo:[['health','Runtime health','Use existing diagnostic owners','Offline scope shown','details'],['coverage','Trace coverage','Check loaded-source evidence','Freshness matters','search'],['indexes','Index health','Graph, memory & learning','Existing maintenance owners','refresh'],['caches','Review MO caches','Generated and retained state','Protect active work','folder']],server:[['health','Host health','Resources and OS','Selected host only','details'],['service','MO service','Deployed service evidence','Separate host state','tools'],['caches','Review host logs','Retention and active writers','No blanket deletion','folder'],['repair','Maintenance plan','Inspect proposed changes','Review before apply','search']],projects:[['health','Project health','Use project and graph owners','Selected root only','search'],['dependencies','Dependencies','Root manifests & graph','Use requires owner review','tools'],['caches','Review caches','Generated outputs and activity','Preserve useful work','folder'],['storage','Storage discovery','Measured selected-root files','Bounded results','details']]};
function quickMarkup(r){const game=r[0]==='game',session=game?state.data?.game_session:null,active=game&&state.data?.game_active;return `<button class="quick${active?' game-active':''}${state.quickActive===r[0]&&state.busy?' is-running':''}${state.quickDone===r[0]?' is-done':''}" data-quick="${r[0]}"><div class="quick-top"><span class="tile-symbol">${icon(r[4])}</span>${mark.replace('mo-mark','mo-mark step-mark')}</div><h3>${game?'Game Session':r[1]}</h3><p>${game?(session?.state==='active'?`Active · ${sessionDuration(session.duration_seconds)}`:session?.state==='recovery_required'?'Recovery needed · restore originals':session?.state==='restored'?'Last session restored':'Start a reviewed global session'):r[2]}</p><small>${state.quickActive===r[0]&&state.busy?'Working at the current safe boundary':state.quickDone===r[0]?'Finished · see the actual receipt':game&&session?.state==='active'?`${metricPercent(session.metrics?.current?.cpu_percent)} CPU · ${metricPercent(session.metrics?.current?.memory_percent)} memory`:r[3]}</small></button>`}
function overview(){const r=observation('resources')?.resources||{},scan=state.data?.status?.last_scan;const rows=findings().filter(f=>['review','attention'].includes(f.severity)).slice(0,4);return `<div class="overview-top"><div class="overview-copy"><p class="eyebrow">${names[state.context]} / Overview</p><h1>${state.context==='machine'?'Review your machine.':state.context==='mo'?'Keep MO working clearly.':state.context==='server'?'Care for the right host.':'Know what a project needs.'}</h1><p class="subtitle">${state.context==='machine'?'Cleaning, services and repairs in one clear view.':'Target, ownership and freshness come before changes.'}</p><div class="coverage-line"><i></i>${state.context==='machine'?`Last scan: ${time(scan?.completed_at)}`:state.target?esc(state.target):state.context==='mo'?'Active local MO profile':'Choose a target to inspect'}</div></div><div class="resource-grid">${state.context==='machine'?resource('CPU',r.cpu_percent==null?'—':r.cpu_percent.toFixed(0),'% observed')+resource('MEMORY',fmt(r.memory_used),'/ '+fmt(r.memory_total))+resource('STORAGE',fmt(r.storage_free),'free')+resource('REVIEW',scan?scan.review_count:'—','findings'):resource('TARGET',state.target?'Selected':state.context==='mo'?'Local':'—','identity')+resource('EVIDENCE',Object.keys(state.data?.observations||{}).length||'—','sections')+resource('STATE',observation('health')?.stale?'stale':observation('health')?.state||'—',observation('health')?'saved inspection':'inspect first')+resource('COVERAGE','Scoped','owner evidence')}</div></div>${state.context==='machine'?gameSessionPanel():''}<div class="section-title"><h2>Quick actions</h2><small>Compact progress & results</small></div><div class="quick-grid">${quicks[state.context].map(quickMarkup).join('')}</div><div class="section-title"><h2>${state.context==='machine'?'Review next':'Last health inspection'}</h2><small>Saved results</small></div>${rows.length?`<div class="panel">${rows.map(row=>findingRow(row)).join('')}</div>`:state.context==='machine'?`<div class="panel"><div class="list-row"><div class="row-copy"><strong>${scan?'No review findings in the last scan':'Ready for inspection'}</strong><p>${scan?'Coverage is limited to the selected scan scope.':'Last results appear here; deeper scans wait for your click.'}</p></div>${button('Scan','scan',true)}</div></div>`:targetOverview()}`}
function targetOverview(){const health=observation('health');if(health)return observationRows(health,'health');return `<div class="panel"><div class="list-row"><div class="row-copy"><strong>${state.target||state.context==='mo'?'Inspect existing owners':'Select the right target'}</strong><p>Check readiness, retained data and unavailable evidence explicitly.</p></div>${button(state.context==='mo'?'Inspect MO':state.target?'Inspect':'Choose target',state.context==='mo'||state.target?'target-inspect':'target',true)}</div></div>`}
function findingRow(f,select=false){return `<div class="list-row">${select?`<input type="checkbox" data-finding="${esc(f.finding_id)}" aria-label="Select ${esc(f.title)}" ${state.selected.has(f.finding_id)?'checked':''} ${f.selectable?'':'disabled'}>`:`<span class="row-symbol">${icon('details')}</span>`}<div class="row-copy"><strong>${esc(f.title)}</strong><p>${esc(f.summary)}</p></div>${f.reclaimable_bytes?`<span class="row-value">${fmt(f.reclaimable_bytes)}</span>`:badge(f.severity)}<button class="quiet" data-detail="${esc(f.finding_id)}">Details ${icon('chevron_right')}</button></div>`}
function clean(){if(state.context!=='machine')return contextView('caches');const tabs={caches:'Caches',system:'System',browser:'Browser',storage:'Storage',recycle:'Recycle Bin'};const rows=findings().filter(f=>f.rule_id.startsWith('storage.')).filter(f=>state.clean==='browser'?f.rule_id.startsWith('storage.browser_'):state.clean==='system'?['storage.wer_old','storage.crash_dumps','storage.windows_temp_advisory','storage.delivery_optimization_advisory'].includes(f.rule_id):f.domain==='storage'&&!/^storage\.(browser_|wer_old|crash_dumps|windows_temp_advisory|delivery_optimization_advisory|disk_pressure)/.test(f.rule_id));return `${heading('Choose what to clean.','Generated data and retained data stay visibly separate.',button('Review selection','review-clean',true))}<div class="page-summary"><div class="summary-stat"><strong>${fmt(state.data?.status?.last_scan?.reclaimable_bytes??null)}</strong><p>Last scan candidates</p></div><div class="summary-copy"><strong>Inspect exact contents before applying.</strong><p>Passwords, critical browser data and active work remain protected.</p></div>${button('Scan','scan')}</div><div class="subtabs">${Object.entries(tabs).map(([k,v])=>`<button data-clean="${k}" class="${state.clean===k?'active':''}">${v}</button>`).join('')}</div>${state.clean==='recycle'?ownerCare('recycle','Windows Recycle Bin'):state.clean==='storage'?storageTools():rows.length?`<div class="panel">${rows.map(f=>findingRow(f,true)).join('')}</div>`:'<div class="panel"><div class="empty">No results for this category.<br><small>Scan its supported owners to inspect candidates.</small></div></div>'}${state.clean==='browser'?ownerCare('browser_data','Local history & downloads'):''}<div class="selectionbar"><span>${state.selected.size} selected · exact contents in review</span><button class="quiet" data-do="exclusions">Protected data & exclusions ${icon('chevron_right')}</button></div>`}
function observationRows(o,section=''){
 if(!o)return noEvidence(section)+(section?askMO(section):'');
 const rows=o.rows||[],actionable=actionableObservation(o);
 return `<div class="panel">${rows.length?rows.map((r,i)=>`<div class="list-row"><div class="row-copy"><strong>${esc(r.name||r.Name||r.Model||r.DeviceID||'Item')}</strong><p>${esc(r.detail||r.Status||r.FileSystem||'')}</p></div>${r.bytes!=null||r.Size!=null?`<span class="row-value">${fmt(r.bytes??r.Size)}</span>`:''}${r.startup?badge('Startup: '+r.startup):''}${badge(r.state||r.Status||'observed')}${['browser_data','recycle','app_leftovers'].includes(section)&&r.eligible&&actionable?button('Review item','action-plan',false,`data-action="${{browser_data:'browser_history_clear',recycle:'recycle_remove',app_leftovers:'app_leftover_remove'}[section]}" data-section="${section}" data-index="${i}" data-observed="${o.observed_at}"`):section==='storage'? (actionable?button('Review optimization','action-plan',false,`data-action="disk_optimize" data-section="storage" data-index="${i}" data-observed="${o.observed_at}"`):'')+button('Check file system','repair-inspect',false,`data-section="filesystem" data-drive="${esc(r.DeviceID)}"`):section==='environment'&&r.state==='duplicate'&&actionable?button('Review duplicate','action-plan',false,`data-action="path_remove_duplicate" data-section="environment" data-index="${i}" data-observed="${o.observed_at}"`):section==='updates'?(r.eula_accepted&&actionable?button('Review update','action-plan',false,`data-action="windows_update" data-section="updates" data-index="${i}" data-observed="${o.observed_at}"`):badge('native interaction')):''}${state.context!=='machine'?button('Review item','item-review',false,`data-section="${esc(section)}" data-index="${i}"`):''}</div>`).join(''):`<div class="empty">${o.state==='unavailable'?'Inspection unavailable.':o.state==='failed'?'Inspection failed.':'No matching items in this inspection.'}</div>`}</div><p class="evidence-note">${esc(o.state)} · ${esc(o.detail||(Array.isArray(o.coverage)?o.coverage.join(' · '):o.coverage)||'')} · ${time(o.observed_at)}${o.stale?' · stale; inspect again before changes':''}</p>${section?askMO(section):''}`;
}
function ownerCare(section,title){return `<div class="section-title"><h2>${title}</h2>${button('Inspect','owner-inspect',false,`data-section="${section}"`)}</div>${observationRows(observation(section),section)}`}
function storageTools(){return `<div class="tool-grid">${[['storage','Drive usage','Current drive capacity'],['devices','Device health','Native disk evidence'],['large','Large files','Selected-root discovery'],['duplicates','Duplicate files','Verified content matches'],['empty','Empty folders','Ownership and exclusions']].map(([id,title,sub])=>`<div class="tool-card"><span class="row-symbol">${icon('folder')}</span><div class="row-copy"><strong>${title}</strong><p>${sub}</p></div>${button('Inspect','storage-tool',false,`data-section="${id}"`)}${observation(id)?button('Results','storage-results',false,`data-section="${id}"`):''}</div>`).join('')}</div>`}
function contextView(section){
 const allowed=state.context==='mo'?['health','indexes','coverage','caches']:state.context==='server'?['health','service','logs','caches','repair']:['health','dependencies','caches','storage'];
 if(!allowed.includes(state.section))state.section=section;
 const selected=state.section,o=observation(selected);
 return `${heading(state.context==='projects'?sectionLabels[selected]+' for your project.':selected==='caches'?'Review owned data.':'Inspect the current system.',state.context==='projects'?'Choose a declared project or explicit folder. Checks cover that selected root; generated names never authorize cleanup.':state.context==='server'?'Selected SSH host · host resources and system/user MO service scopes stay separate.':'Current use and scoped evidence come before changes.',button(state.context==='mo'||state.target?'Inspect':'Choose target',state.context==='mo'||state.target?'target-inspect':'target',true))}<div class="subtabs">${allowed.map(s=>`<button data-target-section="${s}" class="${s===selected?'active':''}">${sectionLabels[s]||s}${sectionEvidence(s)}</button>`).join('')}</div>${observationRows(o,selected)}<p class="evidence-note">Maintenance review uses MO's existing conversation and tools. Changes wait for approval of an exact plan.</p>`;
}
function startupEvidence(m){return `<div class="section-title"><h2>Windows startup measurements</h2></div>${m?.rows?.length?`<div class="panel">${m.rows.slice(0,8).map(r=>`<div class="list-row"><div class="row-copy"><strong>${esc(r.name||'Recorded application')}</strong><p>${esc(r.observed_at)} · Event ${r.source_event}</p></div><span class="row-value">${r.milliseconds} ms</span></div>`).join('')}</div>`:''}<p class="evidence-note">${esc(m?.detail||'Inspect Startup to read available Windows boot/degradation events. No impact is inferred from registration presence.')}</p>`}
function manage(){
 if(state.context!=='machine')return contextView('health');
 const tabs={services:'Services',startup:'Startup',apps:'Apps',app_leftovers:'App leftovers',packaged_apps:'Windows apps',software_updates:'Updates',drivers:'Drivers',driver_updates:'Driver updates',driver_packages:'Driver packages'},o=observation(state.manage),rows=(o?.rows||[]).map((row,index)=>({row,index}));
 const groups=state.manage==='startup'?[['registry','Run registrations'],['task','Startup-trigger tasks'],['folder','Startup folders'],['other','Other recorded sources']]:[['all','']];
 const tables=groups.map(([source,label])=>{const items=source==='all'?rows:rows.filter(({row})=>source==='other'?!['registry','task','folder'].includes(row.source):row.source===source);if(!items.length)return '';return `${label?`<div class="section-title"><h2>${label}</h2><small>${items.length} recorded</small></div>`:''}<div class="panel"><table class="data-table"><thead><tr><th>Item & purpose</th><th class="optional">State / version</th><th>Owner</th><th></th></tr></thead><tbody>${items.map(({row:r,index:i})=>{const title=r.DisplayName||r.name||r.DeviceName||r.Driver||r.Name,detail=r.Name||r.source||r.Publisher||r.InfName||r.OriginalFileName||r.Id||'';return `<tr><td><div class="app-item">${itemSymbol(state.manage,i,o)}<div>${esc(title)}<small>${esc(detail)}</small></div></div></td><td>${esc(r.State||r.state||r.DisplayVersion||r.DriverVersion||r.Version||'—')}</td><td>${esc(r.StartMode||r.DriverProviderName||r.ProviderName||r.Publisher||r.root_key||r.hive||r.Source||r.source||'—')}</td><td><button class="quiet" data-item="${i}" data-section="${state.manage}">Review ${icon('chevron_right')}</button></td></tr>`}).join('')}</tbody></table></div>`}).join('');
 return `${heading('Understand before changing.','This machine only · MO runtime and remote MO services have their own contexts.',button('Inspect current','inventory',true))}<div class="subtabs">${Object.entries(tabs).map(([k,v])=>`<button data-manage="${k}" class="${k===state.manage?'active':''}">${v}${sectionEvidence(k)}</button>`).join('')}</div>${state.manage==='startup'?startupEvidence(o?.measurements):''}${tables||noEvidence(state.manage)}${o?`<p class="evidence-note">${esc(o.detail||'Native inventory')} · ${time(o.observed_at)}${o.stale?' · stale; inspect again before changes':''}</p>`:''}${askMO(state.manage)}`;
}
const repairs=[['integrity','System files','Check Windows integrity; repair separately.'],['component_store','Component store','Analyze servicing; repair or clean separately.'],['updates','Windows Update','Readiness, pending restart and failures.'],['devices','Storage & devices','Health, checks and media-aware maintenance.'],['network','Network','Inspect connectivity and configuration.'],['environment','Environment','Review missing or incorrect references.'],['desktop','Desktop & icons','Specific Refresh+ repairs with measured results.'],['protection','Windows protection','Current protection-owner readiness.']];
function repair(){if(state.context!=='machine')return contextView('health');return `${heading('Repair a specific problem.','See what each check measures and what its action changes.')}<div class="tool-grid">${repairs.map(([id,title,sub])=>`<div class="tool-card"><span class="row-symbol">${icon(id==='desktop'?'refresh':'tools')}</span><div class="row-copy"><strong>${title}</strong><p>${sub}</p></div>${button('Inspect','repair',false,`data-section="${id}"`)}</div>`).join('')}</div><p class="evidence-note">Checks and repairs remain distinct, with progress, restart requirements and actual outcomes.</p>`}
function registry(){const o=observation('registry'),rows=o?.rows||[];return `${heading('Registry, with a reason.','Exact findings, explanations and restorable originals.',button('Scan registry','registry-scan',true))}<div class="workflow"><span>Inspect</span><b>›</b><span>Explain & select</span><b>›</b><span>Back up</span><b>›</b><span>Repair</span><b>›</b><span>Verify / restore</span></div>${rows.length?`<div class="panel">${rows.map((r,i)=>`<div class="list-row"><input type="checkbox" data-registry="${i}" aria-label="Select ${esc(r.name)}" ${state.registrySelected.has(i)?'checked':''} ${r.eligible?'':'disabled'}><div class="row-copy"><strong>${esc(r.name)}</strong><p>${esc(r.detail)}</p></div>${badge(r.state)}<button class="quiet" data-item="${i}" data-section="registry">Details ${icon('chevron_right')}</button></div>`).join('')}</div>${button('Review selected repairs','registry-plan',true)}`:noEvidence('registry')}<p class="evidence-note">${esc(o?.detail||'Uncertain findings remain inspectable.')} Failed or incomplete backup prevents repair.</p>${askMO('registry')}${o?.coverage?.length?`<details class="panel"><summary>Inspection coverage</summary><table class="data-table"><thead><tr><th>Family / hive</th><th>Keys read</th><th>References checked</th><th>Coverage</th></tr></thead><tbody>${o.coverage.map(c=>`<tr><td>${esc(c.family)}<small>${esc(c.hive)}</small></td><td>${c.examined}</td><td>${c.reference_checks??0}</td><td>${c.time_limited?'Time limited':c.denied?'Access limited':c.bounded?'Depth / count limited':'Declared scope read'}</td></tr>`).join('')}</tbody></table></details>`:''}`}
function history(){if(state.context!=='machine'){const rows=Object.entries(state.data.observations||{});return `${heading('Saved inspections.','Latest result for each section of the selected target. Maintenance conversation and machine receipts have separate owners.')}<div class="panel">${rows.length?rows.map(([section,o])=>`<div class="list-row"><div class="row-copy"><strong>${esc(sectionLabels[section]||section)}</strong><p>${time(o.observed_at)} · ${esc(o.detail||o.state)}${o.stale?' · older result':''}</p></div>${badge(o.state)}${button('Details','inspection-results',false,`data-section="${esc(section)}"`)}</div>`).join(''):'<div class="empty">Choose a target and inspect a section. Its latest saved result will appear here.</div>'}</div>`;}
 const receipts=state.context==='machine'?state.data?.receipts||[]:[],scans=state.context==='machine'?state.data?.history||[]:[],observations=Object.entries(state.data?.observations||{}),recovery=state.context==='machine'?state.data?.recovery||[]:[];
 return `${heading('Every change has a receipt.','Target, measured result and recovery belong together.')}<div class="section-title"><h2>Action receipts</h2><small>${names[state.context]}</small></div><div class="panel">${receipts.length?receipts.map(r=>`<div class="list-row"><div class="row-copy"><strong>${esc(r.state)}</strong><p>${esc(r.detail)} · ${time(r.completed_at)}</p></div>${badge(r.verified?'completed':'Review')}${button('Before / after','receipt',false,`data-receipt="${esc(r.receipt_id)}"`)}</div>`).join(''):'<div class="empty">No recorded native action receipts for this context.</div>'}</div>${recovery.length?`<div class="section-title"><h2>Captured originals</h2><small>${recovery.length} eligible recovery records</small></div><div class="panel">${recovery.map(r=>`<div class="list-row"><div class="row-copy"><strong>${esc(r.action.replaceAll('_',' '))}</strong><p>${esc(r.name)} · ${time(r.at)}</p></div>${badge(r.state)}${button('Restore original','restore',false,`data-step="${esc(r.step_id)}"`)}</div>`).join('')}</div>`:''}<div class="section-title"><h2>Saved inspections</h2></div><div class="panel">${observations.map(([s,o])=>`<div class="list-row"><div class="row-copy"><strong>${esc(s)}</strong><p>${time(o.observed_at)} · ${o.rows?.length||0} rows</p></div>${badge(o.stale?'stale':o.state)}</div>`).join('')||'<div class="empty">No inspections retained for this target.</div>'}</div>${scans.length?`<div class="section-title"><h2>Machine scan history</h2></div><div class="panel">${scans.map(s=>`<div class="list-row"><div class="row-copy"><strong>${esc(s.mode)} · ${esc(s.state)}</strong><p>${time(s.completed_at)} · ${s.finding_count} findings</p></div><span class="row-value">${fmt(s.reclaimable_bytes)}</span></div>`).join('')}</div>`:''}`;
}
function render(){if(!state.data)return;const views=state.context==='machine'?['overview','clean','manage','repair','registry','history']:['overview','clean','manage','repair','history'];if(!views.includes(state.view))state.view='overview';$('#sections').innerHTML=views.map(v=>`<button data-view="${v}" class="${v===state.view?'active':''}" ${v===state.view?'aria-current="page"':''}>${v[0].toUpperCase()+v.slice(1)}</button>`).join('');document.querySelectorAll('[data-context]').forEach(b=>{const on=b.dataset.context===state.context;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});$('#target-detail').innerHTML=state.context==='server'||state.context==='projects'?`<button class="quiet" data-do="target">${esc(state.target||'Select target')} ${icon('chevron_right')}</button>`:state.context==='machine'?'Windows · local':'MO profile · local';const pageKey=[state.context,state.target,state.view,state.section,state.manage,state.clean].join('|'),moved=pageKey!==state.pageKey;state.pageKey=pageKey;$('#content').innerHTML=`<div class="page">${({overview,clean,manage,repair,registry,history})[state.view]()}</div>`;if(moved)$('#content').scrollTop=0;renderStatus();loadItemIcons()}
function renderStatus(){renderScanPanel();const busy=state.busy||state.data?.status?.active,progress=state.data?.progress||{};$('.mo-title-identity').classList.toggle('brand-working',Boolean(busy));$('.scan-label').textContent=busy?'Cancel':'Scan';$('#receipt-status').textContent=state.data?.error||(busy?progress.label||'Inspecting current evidence…':`Results retain their scope and freshness · ${names[state.context]}`);$('#receipt-status').classList.toggle('error-text',Boolean(state.data?.error));$('#freshness').textContent=busy?'WORKING':'LAST RESULTS';document.querySelectorAll('[data-quick]').forEach(e=>{e.classList.toggle('is-running',Boolean(busy&&state.quickActive===e.dataset.quick));e.classList.toggle('is-done',state.quickDone===e.dataset.quick)});}
async function load(force=false,progressOnly=false){
 const context=state.context,target=state.target;
 let data=await call('snapshot',context,target,progressOnly);if(context!==state.context||target!==state.target)return;
 if(progressOnly&&(data.busy||data.status.active)){
  state.data={...state.data,...data,status:{...state.data.status,...data.status}};state.busy=true;renderStatus();schedulePoll();return;
 }
 if(progressOnly){data=await call('snapshot',context,target);if(context!==state.context||target!==state.target)return;}
 if(state.data?.observations?.registry?.observed_at!==data.observations?.registry?.observed_at)state.registrySelected.clear();
 const wasBusy=state.busy;state.data=data;if(state.scanMode==null)state.scanMode=data.preferences.scan_mode_default;state.busy=data.busy||Boolean(data.status.active);if(!state.busy){state.scanRequest=null;state.inspectRequest='';}if(wasBusy&&!state.busy&&state.quickActive){state.quickDone=!data.error&&data.status.last_receipt?.verified&&data.status.last_receipt.receipt_id!==state.quickReceipt?state.quickActive:'';state.quickActive=''}
 const signature=JSON.stringify({context,target,view:state.view,section:state.section,manage:state.manage,clean:state.clean,busy:state.busy,game:data.game_session,preferences:data.preferences,status:data.status.last_scan,receipt:data.status.last_receipt,observations:data.observations,recovery:data.recovery,error:data.error});
 if(force||signature!==state.signature){state.signature=signature;render()}else renderStatus();if(state.busy)schedulePoll();else if(state.pendingRepair){const section=state.pendingRepair;state.pendingRepair='';await repairDetails(section)}
}
function schedulePoll(){clearTimeout(pollTimer);if(canRefresh())pollTimer=setTimeout(()=>load(false,true).catch(()=>{}),650)}
async function inspect(section){if(state.busy)return notify('Wait for the current operation or cancel it.');if((state.context==='server'||state.context==='projects')&&!state.target)return chooseTarget(section);if(state.context==='machine'&&['large','duplicates','empty'].includes(section)&&!state.target){state.target=await call('choose_project');if(!state.target)return}const r=await call('inspect',state.context,section,state.target);if(r.started){state.inspectRequest={context:state.context,target:state.target,section};state.scanRequest=null;state.data.progress={phase:'inspection',context:state.context,section};state.busy=true;renderStatus();schedulePoll()}else notify('Another SystemCare operation is active')}
async function scan(){if(state.busy||state.data?.status?.active){await call('cancel');notify('Cancellation requested at the next safe boundary');schedulePoll();return}if(state.context!=='machine')return inspect(state.view==='overview'?'health':state.section);if(state.view==='manage')return inspect(state.manage);if(state.view==='registry')return inspect('registry');if(state.view==='clean'&&['storage','recycle'].includes(state.clean))return inspect(state.clean);if(state.view==='clean'&&state.clean==='browser')return inspect('browser_data');const r=await call('scan',state.scanMode||state.data.preferences.scan_mode_default);if(r.started){state.scanRequest={mode:state.scanMode||state.data.preferences.scan_mode_default,allChecks:false};state.inspectRequest='';state.data.progress={};state.busy=true;renderStatus();schedulePoll()}else notify('Another SystemCare operation is active')}
async function chooseTarget(section=''){state.targetInspection=section;const targets=await call('targets',state.context);if(state.context==='projects'){const projects=targets.projects||[];openDrawer('Choose your project',`<p>MO’s existing declared projects and the current folder. Selecting one scopes read-only checks; it does not install, build or clean anything.</p><div class="panel">${projects.map(p=>`<button class="search-result" data-project="${esc(p.path)}" ${p.path?'':'disabled'}><strong>${esc(p.name)}</strong><small>${esc(p.path||p.detail)} · ${esc(p.source)}</small></button>`).join('')||'<div class="empty">No declared local project folder.</div>'}</div>${button('Choose another folder','project-browse')}`);return}state.serverTargets=targets.servers;openDrawer('Choose MO host',`<p>Existing configured SSH aliases. Configuration alone does not establish health; Service & startup checks matching system and user MO units.</p><div class="panel">${state.serverTargets.length?state.serverTargets.map(s=>`<button class="search-result" data-host="${esc(s)}">${esc(s)}</button>`).join(''):'<div class="empty">No configured host aliases.</div>'}</div>`)}
async function selectProject(path=''){const section=state.targetInspection,p=await call(path?'select_project':'choose_project',...(path?[path]:[]));if(!p)return;state.target=p;state.selected.clear();closeDrawer();await load(true);if(section)await inspect(section)}
async function finding(id){const f=await call('finding',id);openDrawer(f.title,`<p>${esc(f.summary)}</p><div class="panel"><div class="list-row"><div class="row-copy"><strong>${f.item_count} items · ${fmt(f.measured_bytes)}</strong><p>Action: ${esc(f.action)} · ${esc(f.undo)} recovery · ${esc(f.risk)} risk</p></div></div></div><div class="section-title"><h2>Evidence</h2></div><pre class="receipt-detail">${esc(JSON.stringify(f.evidence,null,2))}</pre>${f.candidates?.length?`<div class="section-title"><h2>Exact candidates</h2><small>${f.candidates.length} total</small></div><div class="panel">${f.candidates.slice(0,50).map(c=>`<div class="list-row"><div class="row-copy"><strong>${esc(c.relative_path)}</strong><p>${esc(c.root_key)} · ${fmt(c.size_bytes)}</p></div></div>`).join('')}</div>${f.candidates.length>50?'<p class="evidence-note">First 50 shown; the exact plan retains all selected candidates.</p>':''}`:''}${askMO(f.evidence?.section||f.rule_id,{finding_id:id})}`)}
function gamePlanReview(step){
 const starting=step.action==='game_on',subject=step.subject||{},session=state.data?.game_session||{},hardware=subject.hardware||session.hardware||{};
 const activeItems=new Map((session.items||[]).map(item=>[item.id,item]));
 const rows=starting?[['Windows Game Mode','Enable it and retain the exact registry original.'],['Windows power plan',subject.power_guid?'Use the configured existing scheme; restore the current scheme later.':'Keep the current scheme unchanged.'],['MO scheduled work',subject.pause_schedules?'Pause starts without losing due work.':'Continue normally.'],['Applications and services','No applications are closed and no Windows services are stopped.']]:[['Windows Game Mode','Restore the exact captured registry value.'],['Windows power plan',activeItems.get('power_scheme')?.enabled?'Restore the captured plan.':'No plan change was made.'],['MO scheduled work',activeItems.get('scheduled_work')?.enabled?'Resume starts; due work remains queued.':'Scheduling was not paused.'],['Recovery verification','Keep the journal if any original fails its post-check.']];
 const device=[hardware.cpu_logical?`${hardware.cpu_logical} logical CPU`:'',hardware.memory_bytes?fmt(hardware.memory_bytes)+' memory':'',hardware.gpu_names?.[0]||''].filter(Boolean).join(' · ');
 return `<div class="game-plan-review"><div class="game-plan-title"><span class="tile-symbol">${icon('tools')}</span><div><strong>${starting?'Start a Game Session':'Stop and restore Game Session'}</strong><p>${starting?'One baseline sample, then the existing visible SystemCare refresh.':'Restore only the state captured by this session.'}</p></div></div><div class="game-plan-items">${rows.map(([label,detail])=>`<div><span class="session-state-dot ${starting?'planned':'review'}"></span><span><strong>${label}</strong><small>${detail}</small></span></div>`).join('')}</div>${device?`<p class="evidence-note">Calibrated context · ${esc(device)}</p>`:''}</div>`;
}
function showPlan(p){const gameStep=p.steps.find(s=>s.action==='game_on'||s.action==='game_off');state.plan=p;const rows=gameStep?gamePlanReview(gameStep):`<div class="panel">${p.steps.map(s=>`<div class="list-row"><div class="row-copy"><strong>${esc(s.title)}</strong><p>${s.subject?esc(s.subject.name||s.subject.key||s.subject.drive||s.subject.identity||s.subject.owner||s.subject.kind):s.candidate_count+' exact candidates'} · ${esc(s.undo)} recovery${s.requires_elevation?' · Windows administrator permission required':''}</p>${s.subject?`<details><summary>Captured owner & original</summary><pre class="receipt-detail">${esc(JSON.stringify(s.subject,null,2))}</pre></details>`:''}</div></div>`).join('')}</div>`;const applyLabel=gameStep?(gameStep.action==='game_on'?'Start reviewed session':'Stop and restore originals'):(p.steps.some(s=>s.requires_elevation)?'Apply with Windows permission':'Apply reviewed plan');openDrawer(gameStep?'Review Game Session':'Review exact plan',`<p>${p.steps.length} selected steps${p.expected_bytes?' · '+fmt(p.expected_bytes)+' expected removal':''}</p>${rows}<p class="evidence-note">Captured state is rechecked before applying. Long native operations cancel at their next safe boundary. Completion does not establish improved performance.</p>${p.has_non_undo?'<label><input id="acknowledge" type="checkbox"> I understand that this action has no exact undo.</label>':''}${button(applyLabel,'apply',true)}${askMO('',{plan_id:p.plan_id,digest:p.digest})}`)}
async function reviewPlan(){if(!state.selected.size)return notify('Select current actionable findings first');showPlan(await call('plan',[...state.selected],state.data.status.last_scan.scan_id))}
async function actionPlan(action,section='',indices=[],observedAt=observation(section)?.observed_at??null){if(state.busy)return notify('Wait for the current operation first');showPlan(await call('action_plan',action,section,indices,state.target,observedAt))}
async function openQuick(action,reload=true){if(action!=='game')return false;state.context='machine';state.target='';if(reload)await load(true);await actionPlan(state.data?.game_active?'game_off':'game_on');return true}
async function applyPlan(){const p=state.plan;if(!p)return;const ack=Boolean($('#acknowledge')?.checked);if(p.has_non_undo&&!ack)return notify('Acknowledge permanent removal before applying');const r=await call('apply',p.plan_id,p.digest,ack);if(r.started){state.quickActive=p.steps.some(s=>s.action.startsWith('game_'))?'game':'';state.quickDone='';state.quickReceipt=state.data.status.last_receipt?.receipt_id||'';state.plan=null;closeDrawer();state.busy=true;renderStatus();schedulePoll()}}
function exclusions(){openDrawer('Protected data',`<p>Protection follows ownership, current use and purpose.</p><div class="panel">${['Passwords and saved credentials','Critical browser and active session data','Active work and required dependencies','MO continuity and useful artifacts','Recovery backups and retained diagnostics'].map(n=>`<div class="list-row"><span class="row-copy">${n}</span>${badge('Keep')}</div>`).join('')}</div><p class="evidence-note">Cleanup does not organize folders or change folder preferences.</p>`)}
function settingSwitch(id,title,checked,detail,attributes=''){return `<label class="settings-row" for="${id}"><span class="settings-copy"><strong>${title}</strong><small>${detail}</small></span><input class="settings-switch" type="checkbox" role="switch" id="${id}" ${attributes} ${checked?'checked':''}></label>`}
async function settings(){
 const p=state.data.preferences,a=p.automation,g=p.game_mode;
 const scanLabels={deep_storage:['Deep storage','Inspect protected Windows cache owners.'],component_store:['Windows components','Inspect servicing and component-store readiness.'],system_integrity:['System integrity','Keep checks separate from selected repairs.'],service_advisory:['Services','Review current registrations before changes.'],registry_advisory:['Registry references','Include registry advisory in Advanced scans.']};
 const categoryLabels={storage:'Storage and cleanup',startup:'Startup and services',health:'Windows health',performance:'Performance',registry:'Registry'};
 openDrawer('Settings',`<div class="settings-intro"><p>Make maintenance fit your work.</p><small class="evidence-note">Saved results open immediately. Deep checks wait for your request.</small></div><div class="settings-scroll">
 <section class="settings-group"><div class="settings-group-heading">${icon('search')} Scans & notices</div><label class="settings-row" for="pref-mode"><span class="settings-copy"><strong>Default scan</strong><small>Safe owners or optional Advanced checks.</small></span><select id="pref-mode"><option value="safe" ${p.scan_mode_default==='safe'?'selected':''}>Safe</option><option value="advanced" ${p.scan_mode_default==='advanced'?'selected':''}>Advanced</option></select></label>${settingSwitch('pref-notifications','SystemCare notifications',p.notifications,'Results stay saved even when notices are off.')}<label class="settings-row" for="pref-notification-scope"><span class="settings-copy"><strong>When to notify</strong><small>Visible inspections update their results without a popup by default.</small></span><select id="pref-notification-scope"><option value="background" ${p.notification_scope==='background'?'selected':''}>Background results</option><option value="attention" ${p.notification_scope==='attention'?'selected':''}>Errors & background results</option><option value="all" ${p.notification_scope==='all'?'selected':''}>All results</option></select></label></section>
 <details class="settings-group"><summary>${icon('details')} Advanced checks & categories</summary>${Object.entries(p.advanced).map(([k,v])=>settingSwitch('pref-'+k,scanLabels[k][0],v,scanLabels[k][1],`data-pref="${k}"`)).join('')}<div class="settings-group-heading">Scan categories</div>${Object.entries(categoryLabels).map(([k,n])=>settingSwitch('category-'+k,n,p.categories[k]!==false,'Include this owner in requested scans.',`data-category="${k}"`)).join('')}</details>
 <details class="settings-group"><summary>${icon('tools')} Global Game Mode</summary><p class="settings-note">One on/off control. Captured originals are restored when you switch it off.</p>${settingSwitch('game-pause','Pause MO scheduled work',g.pause_schedules,'Manual MO work stays available while Game Mode is active.')}<label class="settings-row" for="game-power"><span class="settings-copy"><strong>Power scheme</strong><small id="power-detail">Reading existing Windows schemes…</small></span><select id="game-power"><option value="">Keep current</option>${g.power_guid?`<option value="${esc(g.power_guid)}" selected>Saved scheme · checking…</option>`:''}</select></label></details>
 <details class="settings-group"><summary>${icon('refresh')} Optional automation</summary>${[['enabled','Schedule Safe scans','Use the existing MO scheduler; disabled until you enable it.'],['battery_pause','Pause on battery','Also pause when power state is unavailable.'],['game_pause','Pause during Game Mode','Scheduled maintenance waits until the mode ends.'],['cleanup','Allow selected permanent cache cleanup','Only old temp, thumbnail and DirectX caches; no undo.']].map(([k,n,d])=>settingSwitch('auto-'+k,n,a[k],d,`data-auto="${k}"`)).join('')}<div class="settings-grid"><label for="auto-interval">Interval · hours<input id="auto-interval" type="number" min="1" max="168" value="${a.interval_hours}"></label><label for="auto-idle">Minimum idle · minutes<input id="auto-idle" type="number" min="0" max="120" value="${a.idle_minutes}"></label></div></details>
 <details class="settings-group"><summary>${icon('folder')} History & recovery</summary><div class="settings-grid"><label for="pref-retention">Retention · days<input id="pref-retention" type="number" min="1" max="365" value="${p.retention_days}"></label><label for="pref-history">History limit<input id="pref-history" type="number" min="4" max="200" value="${p.history_limit}"></label><label for="pref-ttl">Plan expiry · minutes<input id="pref-ttl" type="number" min="5" max="60" value="${p.plan_ttl_minutes}"></label></div><p class="settings-note">Unrestored recovery originals remain protected. Expired plans require fresh review.</p></details></div><div class="settings-actions">${button('Recalibrate','calibrate')}${button('Save settings','save-settings',true)}</div>`);
 $('#drawer').classList.add('settings-drawer');
 const select=$('#game-power');try{const rows=await call('power_schemes');if(!select.isConnected)return;select.innerHTML='<option value="">Keep current scheme</option>'+rows.map(r=>`<option value="${esc(r.guid)}" ${r.guid===g.power_guid?'selected':''}>${esc(r.name)}</option>`).join('');if(g.power_guid&&!rows.some(r=>r.guid===g.power_guid))select.innerHTML+=`<option value="${esc(g.power_guid)}" selected>Saved scheme · unavailable</option>`;$('#power-detail').textContent='Existing Windows schemes only.'}catch(_error){if(select.isConnected)$('#power-detail').textContent='Unavailable; your saved selection is retained.'}
}
async function saveSettings(){const advanced={},categories={},automation={interval_hours:Number($('#auto-interval').value),idle_minutes:Number($('#auto-idle').value)};document.querySelectorAll('[data-pref]').forEach(e=>advanced[e.dataset.pref]=e.checked);document.querySelectorAll('[data-category]').forEach(e=>categories[e.dataset.category]=e.checked);document.querySelectorAll('[data-auto]').forEach(e=>automation[e.dataset.auto]=e.checked);const r=await call('save_settings',{scan_mode_default:$('#pref-mode').value,advanced_scan:advanced,categories,automation,notifications:$('#pref-notifications').checked,notification_scope:$('#pref-notification-scope').value,game_mode:{pause_schedules:$('#game-pause').checked,power_guid:$('#game-power').value},retention_days:Number($('#pref-retention').value),history_limit:Number($('#pref-history').value),plan_ttl_minutes:Number($('#pref-ttl').value)});notify(r.saved?'Settings saved':r.detail);await load();if(r.saved)closeDrawer()}
function search(){openDrawer('Find a maintenance tool','<input id="tool-search" class="search-input" type="search" placeholder="Services, registry, updates…" aria-label="Find a maintenance tool"><div id="search-results"></div>');filterSearch('');$('#tool-search').focus()}
function filterSearch(q){const rows=state.context==='machine'?[['Game Session','overview'],['Cache cleanup','clean','caches'],['Browser care','clean','browser'],['Storage discovery','clean','storage'],['Services / MO analysis','manage','services'],['Startup apps & tasks','manage','startup'],['Software updates / uninstall','manage','apps'],['Windows packaged apps','manage','packaged_apps'],['Driver management','manage','drivers'],['Windows repairs','repair'],['Comprehensive registry','registry'],['Action history','history']]:[['Owned caches & data','clean'],['Dependencies & health','manage'],['Repairs & recovery','repair'],['History','history']];$('#search-results').innerHTML=rows.filter(r=>r[0].toLowerCase().includes(q.toLowerCase())).map(r=>`<button class="search-result" data-view="${r[1]}" ${r[2]?`data-${r[1]}="${r[2]}"`:''}>${r[0]}<small>${names[state.context]}</small></button>`).join('')||'<p>No matching tool.</p>'}
async function item(section,index){
 const o=observation(section),row=o?.rows?.[index];if(!row)return;
 const actions=state.context!=='machine'||!actionableObservation(o)?[]:section==='services'?['start','stop','restart','automatic','manual','disabled'].map(v=>['service_'+v,v]):section==='startup'?row.source==='task'?[['task_enable','Enable'],['task_disable','Disable']]:row.source==='folder'?[['startup_shortcut_disable','Review shortcut disable']]:row.source==='registry'?[['startup_disable','Disable']]:[]:section==='registry'&&row.eligible?[['registry_remove','Review value removal']]:section==='app_leftovers'&&row.eligible?[['app_leftover_remove','Review leftover removal']]:section==='apps'&&!row.SystemComponent?[['app_uninstall','Review registered uninstall']]:section==='packaged_apps'&&row.can_remove===true?[['app_uninstall','Review removal for this account']]:section==='software_updates'?[['app_update','Review exact package update']]:['updates','driver_updates'].includes(section)&&row.eula_accepted===true?[['windows_update','Review selected Windows update']]:section==='driver_packages'&&row.InUse===false&&row.Inbox===false&&row.BootCritical===false?[['driver_remove','Review unused package removal']]:[];
 openDrawer(row.DisplayName||row.DeviceName||row.Driver||row.name||row.Name||'Item',`<p>${section==='packaged_apps'?'Windows package in this account. Removing it can remove its app data; reinstall and data recovery are separate. Framework and protected packages are inspect-only.':'Review current owner, state and impact.'}</p><pre class="receipt-detail">${esc(JSON.stringify(row,null,2))}</pre>${state.context==='machine'?button('Inspect exact item','item-inspect',true,`data-section="${section}" data-index="${index}" data-observed="${o.observed_at}"`):''}${askMO(section,{index,observed_at:o.observed_at})}<div class="tool-grid">${actions.map(([a,n])=>button(n,'action-plan',false,`data-action="${a}" data-section="${section}" data-index="${index}" data-observed="${o.observed_at}"`)).join('')}</div>`);
}
async function repairDetails(section){
 const o=observation(section),actions=section==='integrity'?[['integrity_repair','Review system-file repair']]:section==='component_store'?[['component_repair','Review component repair'],['component_cleanup','Review component cleanup']]:section==='network'?[['network_dns','Review DNS cache reset']]:[],readiness=o?.readiness||[];
 openDrawer(repairs.find(r=>r[0]===section)?.[1]||(section==='filesystem'?'File-system check':'Repair'),`<p>Inspect the selected Windows owner before choosing a repair.</p>${observationRows(o,section)}${readiness.length?`<div class="section-title"><h2>Servicing readiness</h2></div><div class="panel">${readiness.map(r=>`<div class="list-row"><div class="row-copy"><strong>${esc(r.name)}</strong><p>${esc(r.detail)}</p></div>${badge(r.state)}</div>`).join('')}</div>`:''}${button('Inspect native owner','repair-inspect',true,`data-section="${section}" data-drive="${esc(o?.drive||'')}"`)}${actionableObservation(o)?actions.map(([a,n])=>button(n,'repair-plan',false,`data-action="${a}" data-section="${section}"`)).join(''):''}`)
}
document.addEventListener('input',e=>{if(e.target.id==='tool-search')filterSearch(e.target.value)});
document.addEventListener('change',e=>{if(e.target.id==='scan-advanced'){state.scanMode=e.target.checked?'advanced':'safe';renderScanPanel();return}if(e.target.dataset.finding){e.target.checked?state.selected.add(e.target.dataset.finding):state.selected.delete(e.target.dataset.finding)}if(e.target.dataset.registry!==undefined){const index=Number(e.target.dataset.registry);e.target.checked?state.registrySelected.add(index):state.registrySelected.delete(index)}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{
 if(b.dataset.scanDomain){scanDetails(b.dataset.scanDomain);return}
 if(b.dataset.scanCheck){const evidence=operationEvidence(),c=evidence.checks.find(c=>(c.step_id||c.rule_id)===b.dataset.scanCheck);if(!c)return;if(c.step_id){openDrawer(c.title,`<p>${esc(checkLabels[c.state])}${c.at?' · '+time(c.at):''}</p><p>${esc(c.detail||'This step has not returned its post-check yet.')}</p>${evidence.repairResult?button('Before / after','receipt',false,`data-receipt="${esc(evidence.receipt.receipt_id)}"`):''}`);return}if(c.section){openDrawer(c.title,`<p>${esc(checkLabels[c.state])}${c.stale?' · older result':''}${c.at?' · '+time(c.at):''}</p>`+observationRows(observation(c.section),c.section));}else{const f=findings().find(f=>f.rule_id===c.rule_id);if(f)await finding(f.finding_id);else openDrawer(c.title,`<p>${esc(checkLabels[c.state])}. No result recorded yet.</p>`);}return}
 if(b.dataset.window){if(b.dataset.window==='close')await requestClose();else await call('window_control',b.dataset.window);return}
 if(b.dataset.context){state.context=b.dataset.context;state.target='';state.section='health';state.registrySelected.clear();state.selected.clear();state.plan=null;closeDrawer();await load(true);return}
 if(b.dataset.project){await selectProject(b.dataset.project);return}
 if(b.dataset.host){const section=state.targetInspection;state.target=b.dataset.host;closeDrawer();await load(true);if(section)await inspect(section);return}
 if(b.dataset.targetSection){state.section=b.dataset.targetSection;render();return}
 if(b.dataset.view){state.selected.clear();if(state.context!=='machine'&&state.view!==b.dataset.view)state.section=b.dataset.view==='clean'?'caches':b.dataset.view==='repair'&&state.context==='server'?'repair':b.dataset.view==='manage'&&state.context==='projects'?'dependencies':'health';state.view=b.dataset.view;if(b.dataset.clean)state.clean=b.dataset.clean;if(b.dataset.manage)state.manage=b.dataset.manage;closeDrawer();render();return}
 if(b.dataset.clean){state.clean=b.dataset.clean;render();return}if(b.dataset.manage){state.manage=b.dataset.manage;render();return}
 if(b.dataset.detail){await finding(b.dataset.detail);return}if(b.dataset.item){await item(b.dataset.section,Number(b.dataset.item));return}
 if(b.dataset.quick){const q=b.dataset.quick;if(state.context!=='machine'){state.section=q;state.view=['caches','storage'].includes(q)?'clean':'manage';render();await inspect(q);return}if(q==='game'){await actionPlan(state.data.game_active?'game_off':'game_on');return}if(q==='icons'){state.view='clean';state.clean='caches';render();await scan();return}if(q==='integrity'){state.view='repair';render();await repairDetails('integrity');return}const r=await call('quick_action',q);if(r.started){state.quickActive=q;state.quickDone='';state.quickReceipt=state.data.status.last_receipt?.receipt_id||'';state.busy=true;renderStatus();schedulePoll()}return}
 const a=b.dataset.do;if(a==='background-close'||a==='stop-close'){await call('window_control',a==='stop-close'?'stop_close':'background_close');return}if(a==='close'){closeDrawer();return}if(a==='search'){search();return}if(a==='settings'){await settings();return}if(a==='save-settings'){await saveSettings();return}
 if(a==='project-browse'){await selectProject();return}
 if(a==='scan-all'){await scanAll();return}if(a==='scan-scope'){scanScope();return}if(a==='scan'){await scan();return}if(a==='target'){await chooseTarget();return}if(a==='target-inspect'){await inspect(state.section);return}if(a==='inventory'){await inspect(state.manage);return}
 if(a==='repair-all'){await repairAll();return}if(a==='review-clean'){await reviewPlan();return}if(a==='game-session-review'){await actionPlan(state.data?.game_active?'game_off':'game_on');return}if(a==='apply'){await applyPlan();return}if(a==='exclusions'){exclusions();return}
 if(a==='calibrate'){const r=await call('calibrate');if(r.started){closeDrawer();state.busy=true;renderStatus();schedulePoll()}return}
 if(a==='repair'){await repairDetails(b.dataset.section);return}if(a==='storage-tool'||a==='owner-inspect'){await inspect(b.dataset.section);return}
 if(a==='item-review'){await item(b.dataset.section,Number(b.dataset.index));return}
 if(a==='inspection-results'){openDrawer(sectionLabels[b.dataset.section]||b.dataset.section,observationRows(observation(b.dataset.section),b.dataset.section));return}
 if(a==='storage-results'){openDrawer('Storage inspection',observationRows(observation(b.dataset.section),b.dataset.section));return}
 if(a==='maintenance-review'){b.disabled=true;try{const r=await call('request_maintenance',b.dataset.contextReview,b.dataset.section,b.dataset.target,JSON.parse(b.dataset.selection||'null'));notify(r.queued?'Review requested in MO’s existing conversation':'MO did not confirm this request')}finally{b.disabled=false}return}
 if(a==='registry-scan'){state.registrySelected.clear();await inspect('registry');return}
 if(a==='registry-plan'){await actionPlan('registry_remove','registry',[...state.registrySelected]);return}
 if(a==='action-plan'){await actionPlan(b.dataset.action,b.dataset.section,[Number(b.dataset.index)],Number(b.dataset.observed));return}
 if(a==='restore'){const r=await call('restore',b.dataset.step);if(r.started){closeDrawer();state.busy=true;renderStatus();schedulePoll()}return}
 if(a==='repair-plan'){await actionPlan(b.dataset.action,b.dataset.section);return}
 if(a==='repair-inspect'){const r=await call('native_check',b.dataset.section,b.dataset.drive||'');if(r.started){state.pendingRepair=b.dataset.section;closeDrawer();state.busy=true;renderStatus();schedulePoll()}return}
 if(a==='item-inspect'){const r=await call('inspect_item',b.dataset.section,Number(b.dataset.index),Number(b.dataset.observed));openDrawer('Exact item evidence',`<pre class="receipt-detail">${esc(JSON.stringify(r,null,2))}</pre>${askMO(b.dataset.section,{index:Number(b.dataset.index),observed_at:Number(b.dataset.observed)})}`);return}
 if(a==='receipt'){
  const r=await call('receipt',b.dataset.receipt||state.data.status.last_receipt.receipt_id),recoverable=new Set(state.data.recovery.map(row=>row.step_id));
  openDrawer('Apply receipt',`<div class="measure-comparison"><div><label>RESULT</label><strong>${esc(r.state)}</strong></div><div class="after"><label>RECORDED REMOVAL</label><strong>${fmt(r.reclaimed_bytes)}</strong></div></div><p>${esc(r.detail)}</p><p class="evidence-note">${r.applied_steps.length} applied · ${r.skipped_steps.length} skipped · ${r.failed_steps.length} failed · ${time(r.completed_at)}</p>${r.originals.map(row=>`<div class="section-title"><h2>${esc(row.action)}</h2>${badge(row.state)}</div><pre class="receipt-detail">${esc(JSON.stringify({before:row.original,after:row.after??'No complete post-state',output:row.output||undefined},null,2))}</pre>${recoverable.has(row.step_id)?button('Restore original','restore',false,`data-step="${esc(row.step_id)}"`):''}`).join('')}`);
 }
 }catch(_error){/* The call boundary already showed the actual failure. */}
});
$('#scrim').addEventListener('click',closeDrawer);document.addEventListener('keydown',e=>{if(e.key==='Tab'&&!$('#drawer').hidden){const items=[...$('#drawer').querySelectorAll('button,input,select,summary,[tabindex]')].filter(el=>!el.disabled&&el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}if(e.key==='Escape')closeDrawer();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search()}});
$('#resize-grip').addEventListener('pointerdown',e=>{e.preventDefault();const x=e.screenX,y=e.screenY,w=window.innerWidth,h=window.innerHeight;const resize=m=>call('window_control','resize',w+m.screenX-x,h+m.screenY-y).catch(()=>{});document.addEventListener('pointermove',resize);document.addEventListener('pointerup',()=>document.removeEventListener('pointermove',resize),{once:true})});
window.moCareApplyTheme=css=>$('#mo-care-theme').textContent=css;
window.moCareOpenQuick=action=>openQuick(action,true).catch(error=>notify(error.message||String(error)));
window.moCareSetVisible=value=>{hostVisible=Boolean(value);clearTimeout(pollTimer);clearTimeout(refreshTimer);if(canRefresh()){load().catch(()=>{});lightRefresh()}return canRefresh()};
document.addEventListener('visibilitychange',()=>window.moCareSetVisible(hostVisible));
function lightRefresh(){clearTimeout(refreshTimer);if(!canRefresh())return;refreshTimer=setTimeout(async()=>{if(canRefresh()&&state.context==='machine'&&!state.busy){try{await inspect('resources')}catch(_error){}}lightRefresh()},15000)}
window.addEventListener('pywebviewready',async()=>{try{await load(true);await call('ui_ready');if(initial.start_scan)await scan();else if(initial.quick_action)await openQuick(initial.quick_action,false);else if(state.context==='machine')await inspect('resources');lightRefresh()}catch(e){$('#content').textContent='SystemCare could not load: '+(e.message||String(e));await api().ui_ready()}});
})();
